name: Merge Develop to Main

on:
  push:
    branches:
      - 'develop'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge develop to main
        run: |
          git config user.name sangyoon
          git config user.email lsyo6171@gmail.com
          git checkout main
          git merge --no-ff origin/develop
          git push origin main
