name: Merge Develop to Main

on:
  push:
    branches:
      - 'develop'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Merge develop to main
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          from_branch: develop
          to_branch: main
